[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true

[api]
  dashboard = true
  insecure = true  # Be careful with this in production!

[certificatesResolvers.letsencrypt.acme]
  email = "thuyein1996alpha@gmail.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.letsencrypt.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 30
    resolvers = ["1.1.1.1:53", "8.8.8.8:53"]